spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/database
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    org:
      springframework:
        cache: TRACE

redis:
  host: localhost
  port: 6379